version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
  redis:
    image: "redis:7.2.3"
    ports:
      - "6379:6379"
  develop:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - growthbook
      - redis
    env_file:
      - develop.env
    ports:
      - "8090:8080"
  production:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - growthbook
      - redis
    env_file:
      - production.env
    ports:
      - "8091:8080"
volumes:
  uploads:
  mongodata:
